### ISSUE TITLE
error when runing" ./preprocess.sh "

### ISSUE THREAD

**Issue by pengfzhou** [thu-pacman/HyQuas#1]
/home/zpf/mycode/HyQuas/src/evaluator.h:117:5: error: array must be initialized with a brace-enclosed initializer
/home/zpf/mycode/HyQuas/src/evaluator.h:117:5: error: array must be initialized with a brace-enclosed initializer
/home/zpf/mycode/HyQuas/src/evaluator.h:117:5: error: array must be initialized with a brace-enclosed initializer
/home/zpf/mycode/HyQuas/src/evaluator.h:117:5: error: array must be initialized with a brace-enclosed initializer
/home/zpf/mycode/HyQuas/src/evaluator.h:117:5: error: array must be initialized with a brace-enclosed initializer
/home/zpf/mycode/HyQuas/src/evaluator.h:117:5: error: array must be initialized with a brace-enclosed initializer
src/CMakeFiles/QCSimulator.dir/build.make:924: recipe for target 'src/CMakeFiles/QCSimulator.dir/compiler.cpp.o' failed
make[2]: *** [src/CMakeFiles/QCSimulator.dir/compiler.cpp.o] Error 1
CMakeFiles/Makefile2:265: recipe for target 'src/CMakeFiles/QCSimulator.dir/all' failed
make[1]: *** [src/CMakeFiles/QCSimulator.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by heheda12345** [comment]
Seems to be a problem from g++ version. The system can be compiled with g++ 8.3.0.

**Comment by pengfzhou** [comment]
I modify arrar in the evaluator.h, the error "array must be initialized with a brace-enclosed initializer" is canceled, but I come into another error,"fatal error: cuComplex.h: No such file or directory " and "fatal error: cuda.h: No such file or directory".  but /usr/local/cuda include the two header files.

**Comment by heheda12345** [comment]
You can try to write a simple C++ program that include these two headers to debug your environment variables first.

**Comment by pengfzhou** [comment]
with this command "g++ -I /usr/local/cuda/include  -o test test.cpp" , my helloworld can be compiled, so how to set the environment variables?

**Comment by pengfzhou** [comment]
i have fixed the error by specifying the environment variables, thanks!
