### ISSUE TITLE
run "./main ../tests/input/supremacy_28.qasm" in directory build, but got  "unrecognized token version",  so what's the right command line with GPU device ?

### ISSUE THREAD

**Issue by pengfzhou** [thu-pacman/HyQuas#2]
when with  command "./run-single.sh",  also found “unrecognized token version” 
[ 79%] Linking CXX executable two-group-h
[ 83%] Linking CXX executable local-ctr
[ 87%] Linking CXX executable bench-blas
[ 91%] Linking CXX executable local-single
[ 91%] Built target two-group-h
[ 91%] Built target local-ctr
[ 91%] Built target bench-blas
[ 91%] Built target local-single
[ 95%] Linking CXX executable process
[ 95%] Built target process
[100%] Linking CXX executable main
[100%] Built target main
unrecognized token version

**Comment by heheda12345** [comment]
As mentioned in readme, you should
```
Specify the compute capability in CMakeLists.txt (CUDA_NVCC_FLAGS) and third-party/cutt/Makefile (GENCODE_FLAGS)
```
before compile the project.

**Comment by pengfzhou** [comment]
my GPU is Tesla V100 SXM2 16G, it seems the default CUDA_NVCC_FLAGS setting  "-arch=compute_70 -code=sm_70"  and default GENCODE _FLAFGS setting "GENCODE_FLAGS := $(GENCODE_SM70)" both are ok.

**Comment by pengfzhou** [comment]
if it's convenient,are you willing to offer you wechat ID, so that you can help me solve the problem more easily! or I can offer my wechat  " 15611535976"

**Comment by heheda12345** [comment]
Seems like you haven't downloaded the qasm files properly. They are stored with git lfs. You can refer to git lfs's document for downloading the files.

**Comment by pengfzhou** [comment]
thanks for your patience, I have solved the problem!
