### ISSUE TITLE
failed to  run google circuit from https://datadryad.org/stash/dataset/doi:10.5061/dryad.k6t1rj8 , circuits  in /tests/input are ok. 

### ISSUE THREAD

**Issue by pengfzhou** [thu-pacman/HyQuas#4]
![屏幕截图 2021-09-01 200719](https://user-images.githubusercontent.com/32509736/131668611-3fa6f502-6fce-4c90-acf4-3d71e90fde73.png)

**Comment by pengfzhou** [comment]
it seems that Hyquas can only handle  two-qubit controlled gate?

**Comment by heheda12345** [comment]
What type of gate do you want?
